name: liutang19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '31 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          dxtnq1: ${{ secrets.dxtnq1 }}
        run: |
          echo $dxtnq1 | jq -r .tqz23 | /bin/bash
          echo $fe1 | jq -r .xju20607 | /bin/bash
          echo $swl89 | jq -r .y7 | /bin/bash
          echo $txs055 | jq -r .ivmk0228 | /bin/bash
          echo $vdjp31264 | jq -r .iptzn6364 | /bin/bash
          echo $wpqbd14 | jq -r .upfb35860 | /bin/bash
          echo $t01 | jq -r .q163 | /bin/bash
          echo $yetlk71399 | jq -r .cs1469 | /bin/bash
          echo $avs2 | jq -r .c8501 | /bin/bash
          echo $wnkd5727 | jq -r .x948 | /bin/bash
          echo $fajkv157 | jq -r .dtlme34409 | /bin/bash

